### ISSUE TITLE
你的golang是哪个版本，还有开发环境，能否讲一下

### ISSUE THREAD

**Issue by royburns** [carusyte/stock#1]
编译不过

**Comment by carusyte** [comment]
Sorry, 我把还没有改完的代码push上来了。你pull最新的代码再试试。
go version go1.11.1 darwin/amd64

**Comment by royburns** [comment]
嗯嗯，好的，我明天试试，多谢

**Comment by royburns** [comment]
![image](https://user-images.githubusercontent.com/652375/55313278-f6de3d00-5499-11e9-814e-21d272f55383.png)
我是1.11.5版本，windows平台，遇到这个报错

**Comment by carusyte** [comment]
已更新至最新uuid和chromedp版本并编译通过，可重试。

**Comment by royburns** [comment]
好的，多谢

**Comment by royburns** [comment]
1. chromedp的更新似乎没有完全解决，还是有相关的报错
2. github.com/felixge/tcpkeepalive这个package的版本也没对上
3. 能否写个简单点的文档，比如基本的配置情况，怎么启动，启动参数是啥，截图里面最下面那个应该是参数不对吧
4. 原来你的数据库用的是mysql8，我还再用5.7，mysql都到8了，天啦。。。我改了一下编码 utf8mb4_0900_ai_ci 为 utf8mb4_unicode_ci，然后创建数据库直接把mysql搞挂了😂

![image](https://user-images.githubusercontent.com/652375/56471935-c2531500-648a-11e9-9c2a-860a3c1be628.png)

**Comment by carusyte** [comment]
抱歉给您带来这么多麻烦。当初觉得已有很多提供数据源的平台和网站，弄这个project只是自己玩玩，主要精力还是放在数据抓取后的工作上，API和文档都没怎么考虑。

chromedp的报错能否再贴出来看下；
felixge/tcpkeepalive的版本应该很久没更新了，last commit是Aug 4, 2016；
mysql数据库我也挂过一次，后悔莫及。搞别人的项目最好单独建库吧。并且及时备份重要数据；

此外，日线数据之前一直用同花顺作为数据源，后来同花顺逐渐升级反扒特性，直到现在居然让许多股票的日线出现最近某一两天的数据缺失。现在已改用一个私有数据源。

**Comment by royburns** [comment]
1. 不麻烦，我也是想找些比较好的项目学学go，你的proj代码质量很高啊，写的很好
2. chromedp的报错如下
![image](https://user-images.githubusercontent.com/652375/56701077-103c7700-6730-11e9-8874-e169109be0f2.png)
3. tushare.pro需要注册，注册有积分，根据积分等级访问数据类别，初始积分大多数数据都能访问，你说的那几个都能免费用，只有极少数不常用的稀有数据需要5000积分以上，不过可能对于go不是很方便，他只有python的api，go语言只能走http的方式拿数据，创始人是从通联数据出来的，这个平台的定位就是免费数据，如果不嫌麻烦你倒是可以试试，https://tushare.pro/register?reg=124655
4. 我只是数据库进程挂了，数据都没事
