### ISSUE TITLE
bug1，待确认

### ISSUE THREAD

**Issue by royburns** [carusyte/stock#2]
file: getd\kdj.go
line: 980

fdv.Fid = fmt.Sprintf("%s", uuid.NewV1())

修改为

u1 := uuid.Must(uuid.NewV1())
fdv.Fid = fmt.Sprintf("%s", u1)

正确的用法应该是下面的代码
不知道你那边为啥没有错误，可能是平台相关？

我是windwos平台，go 1.11.5

**Comment by carusyte** [comment]
我这边是17年下下来的uuid的package satori/go.uuid，已经许久未更新。应该跟这个包的版本有关系

**Comment by royburns** [comment]
嗯了解了，go也像python一样有版本问题了，不过现在好像有个解决方案交godef？还是啥的，可以指定引用模块的版本

**Comment by carusyte** [comment]
gopkg.in

**Comment by carusyte** [comment]
你最新版本的chromedp能编译通过？
```
# github.com/chromedp/chromedp
./actions.go:64:19: cannot convert func literal (type func(context.Context, <T>) error) to type ActionFunc
./actions.go:64:49: undefined: cdp.Handler
```

**Comment by carusyte** [comment]
已更新代码，确认编译通过，先关闭这个问题了
