### ISSUE TITLE
bug2，待确认

### ISSUE THREAD

**Issue by royburns** [carusyte/stock#3]
file: getd\kline_ths.go
line: 639, 643, 716, 720

echan := th.Listen(cdproto.EventNetworkRequestWillBeSent, cdproto.EventNetworkLoadingFinished,
			cdproto.EventNetworkLoadingFailed)
		go func(echan <-chan interface{}, ctxt context.Context, fin chan error) {
			defer func() {
				th.Release(echan)
				close(fin)
			}()
![image](https://user-images.githubusercontent.com/652375/55315115-3ad34100-549e-11e9-834c-c44f98ff0194.png)

TargetHandler没有Listen和Release这两个函数

https://godoc.org/github.com/chromedp/chromedp
![image](https://user-images.githubusercontent.com/652375/55315152-50e10180-549e-11e9-821b-4b8ae4bbef00.png)

不确定代码里面的用法是否正确
我是windwos平台，go 1.11.5

**Comment by royburns** [comment]
这个应该是chromedp的版本问题，我用的最新的 = =

**Comment by carusyte** [comment]
你最新版本的chromedp能编译通过？

```
# github.com/chromedp/chromedp
./actions.go:64:19: cannot convert func literal (type func(context.Context, <T>) error) to type ActionFunc
./actions.go:64:49: undefined: cdp.Handler
```

**Comment by royburns** [comment]
应该是能，没有报你这个错

**Comment by carusyte** [comment]
已更新代码，确认编译通过，关闭这个问题了
