### ISSUE TITLE
数据更新的方式

### ISSUE THREAD

**Issue by royburns** [carusyte/stock#5]
我看你代码里面的股票数据获取的方式，似乎都是去相关网站上抓取的，所以你需要搞个代理池，避免反爬，能否把大部分k线数据用类似tushare.pro的开源的数据供应商替代，其他的没有的再去相关网站上抓取，这样压力小很多。

而且有些数据网站的链接可能已经换了，比如
http://stock.finance.qq.com/corp1/plate.php?zqdm=300697

访问之后自动跳转到
https://new.qq.com/ch/finance_stock/

**Comment by carusyte** [comment]
tushare用过，抓取的数据不符合我的使用需求，比如没有前、后复权数据，财务数据不准确或不完整等等问题；tushare.pro还没用过，感觉需要收费

不同种类的数据会根据配置取自不同网站，industry的信息我现在是从同花顺网站取，不会走qq。

我上传了一份stock.sample.toml，仅供参考。
